const sampleData = [
    {
      id: 1,
      image: "/chemical1.jpg",
      title: "Introduction",
      name: "(1R-cis)-Milnacipran Hydrochloride",
      productNumber: "ACA-160613-0004",
      parentDrug: "Milnacipran",
      casNumber: "175131-61-0",
      link1:"/services/web-development",
      category: "Drug Substance Reference Standards",
    },
    {
      id: 2,
      image: "/chemical2.jpg",
      title: "development",
      name: "(2S,3R)-Dihydroxybutanedioic Acid",
      productNumber: "ACA-160614-0005",
      parentDrug: "Tartaric Acid",
      casNumber: "87-69-4",
      link1:"/services/web-development",
      category: "Organic Acid Reference Standards",
    },
    {
        id: 3,
        image: "/chemical1.jpg",
        title: "designing",
        name: "(3R-cis)-Milnacipran Hydrochloride",
        productNumber: "ACA-160613-0004",
        parentDrug: "Milnacipran",
        casNumber: "175131-61-0",
        link1:"/services/web-development",
        category: "Drug Substance Reference Standards",
      },
      {
        id: 4,
        image: "/chemical1.jpg",
        title: "managing",
        name: "(4R-cis)-Milnacipran Hydrochloride",
        productNumber: "ACA-160613-0004",
        parentDrug: "Milnacipran",
        casNumber: "175131-61-0",
        link1:"/services/web-development",
        category: "Drug Substance Reference Standards",
      },
      {
        id: 5,
        image: "/chemical1.jpg",
        title: "deploying",
        name: "(5R-cis)-Milnacipran Hydrochloride",
        productNumber: "ACA-160613-0004",
        parentDrug: "Milnacipran",
        casNumber: "175131-61-0",
        link1:"/services/web-development",
        category: "Drug Substance Reference Standards",
      },
  ];
  
  export default sampleData;
  